export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SET_CURRENT_BITCOIN_NUMBER = "SET_CURRENT_BITCOIN_NUMBER"
export const INSERT_NEW_TRANSACTION = "INSERT_NEW_TRANSACTION"
export const SET_TRANSACTION_LIST = "SET_TRANSACTION_LIST"